# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI Coverage

on:
  push:
    branches: main
  pull_request:
    branches:
      - '*'

jobs:
  coverage:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.18.4]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # solves issue https://github.com/actions/setup-node/issues/214
      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf
          ssh://git@github.com/
      - name: npm ci
        run: npm ci
        env:
          INFURA_API_KEY: ${{secrets.INFURA_API_KEY}}
          MNEMONIC: ${{secrets.MNEMONIC}}
      - name: npm run coverage
        run: npm run coverage
        env:
          INFURA_API_KEY: ${{secrets.INFURA_API_KEY}}
          MNEMONIC: ${{secrets.MNEMONIC}}
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          file: ./coverage.json
          fail_ci_if_error: true